apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: firefly-core-1
  name: firefly_core_1
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
    - name: "5201"
      port: 5201
      targetPort: 5201
  selector:
    io.kompose.service: firefly-core-1
status:
  loadBalancer: {}
